//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "document_chunks")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub id: String,
    #[sea_orm(column_type = "Text")]
    pub document_metadata_id: String,
    #[sea_orm(column_type = "Text")]
    pub collection_metadata_id: String,
    #[sea_orm(column_type = "Text")]
    pub content: String,
    #[sea_orm(column_type = "Blob")]
    pub dense_text_vector: Vec<u8>,
    pub chunk_order: i64,
    #[sea_orm(
        belongs_to,
        from = "document_metadata_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub documents: HasOne<super::documents::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
