//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

pub mod prelude;

pub mod collections;
pub mod document_chunks;
pub mod documents;
pub mod metadata_settings;
pub mod user_resources;
pub mod users;
