//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "payloads")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub block_id: Uuid,
    pub created_at: i64,
    pub last_modified: i64,
    #[sea_orm(column_type = "Text")]
    pub texts: String,
    #[sea_orm(column_type = "Binary(1)")]
    pub bytes: Vec<u8>,
    pub vector: Json,
    pub content_type: String,
    #[sea_orm(
        belongs_to,
        from = "block_id",
        to = "id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    pub blocks: HasOne<super::blocks::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
