//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

pub use super::blocks::Entity as Blocks;
pub use super::metadata_settings::Entity as MetadataSettings;
pub use super::payloads::Entity as Payloads;
