//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "blocks")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub parent_id: Option<String>,
    pub is_deleted: bool,
    #[sea_orm(
        self_ref,
        relation_enum = "SelfRef",
        from = "parent_id",
        to = "id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    pub blocks: HasOne<Entity>,
    #[sea_orm(has_many)]
    pub payloads: HasMany<super::payloads::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
