[package]
name = "opennote-mcp-server"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
# Internal dependencies
opennote-models = { workspace = true }
opennote-bootstrap = { workspace = true }

# External dependencies
actix-web.workspace = true
tokio.workspace = true
rmcp = { version = "3.1.2", features = ["server", "transport-io", "transport-streamable-http-server"] }
anyhow.workspace = true
rmcp-actix-web = { path = "./rmcp-actix-web" }
serde_json.workspace = true
serde.workspace = true
schemars.workspace = true
uuid.workspace = true
async-trait.workspace = true
log.workspace = true
