//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "collections")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub id: String,
    #[sea_orm(column_type = "Text")]
    pub title: String,
    pub created_at: i64,
    pub last_modified: i64,
    #[sea_orm(has_many)]
    pub documents: HasMany<super::documents::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
