//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "documents")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    pub collection_metadata_id: String,
    pub title: String,
    pub created_at: i64,
    pub last_modified: i64,
    #[sea_orm(
        belongs_to,
        from = "collection_metadata_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub collections: HasOne<super::collections::Entity>,
    #[sea_orm(has_many)]
    pub document_chunks: HasMany<super::document_chunks::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
